### ISSUE TITLE
Notify email doesn't get sent if email(webadmin mail) is null or empty

### ISSUE THREAD

**Issue by blevai13** [nathanwoulfe/Plumber#10]
On notify send when workflow approved and completed the notification email doesn't get sent becuase email is empty and it throws error.
Thanks

**Comment by nathanwoulfe** [comment]
Thought I'd fixed this - should be set to the default Umbraco admin email if no settings value exists... My bad.

**Comment by nathanwoulfe** [comment]
Resolved in latest build - email uses default from umbracosettings.config unless an address has been set on the settings node.
