### ISSUE TITLE
Unable to start Umbraco

### ISSUE THREAD

**Issue by Asadlerpwcom** [nathanwoulfe/Plumber#100]
**Describe the bug**
When i install the NuGet package and then try to start the website i get the following error:
```
<Error><Message>An error has occurred.</Message><ExceptionMessage>The object has not yet been initialized. Ensure that HttpConfiguration.EnsureInitialized() is called in the application's startup code after all other initialization code.</ExceptionMessage><ExceptionType>System.InvalidOperationException</ExceptionType><StackTrace>   at System.Web.Http.Routing.RouteCollectionRoute.get_SubRoutes()
   at System.Web.Http.Routing.RouteCollectionRoute.GetRouteData(String virtualPathRoot, HttpRequestMessage request)
   at System.Web.Http.WebHost.Routing.HttpWebRoute.GetRouteData(HttpContextBase httpContext)</StackTrace></Error>
```

The site starts and works perfectly before this package is installed.

I am trying to install 1.1.4 with WebApi version 5.2.6

**Comment by nathanwoulfe** [comment]
Umbraco version?

**Comment by Asadlerpwcom** [comment]
Version 7.13.2

**Comment by nathanwoulfe** [comment]
Ta. Will have a look. Don't think I've run against 13.2 at all.

**Comment by Asadlerpwcom** [comment]
Just incase it helps, i have enabled cors by changing global.asax to:

`<%@ Application Inherits="PharmiWebPortal.MyApplication" Language="C#" %>`

MyApplication.cs in App_Start is:
```

using System;
using System.Web.Http;

namespace PharmiWebPortal
{
    public class MyApplication : Umbraco.Web.UmbracoApplication
    {
        protected override void OnApplicationStarting(object sender, EventArgs e)
        {
            base.OnApplicationStarting(sender, e);
            GlobalConfiguration.Configure(WebApiConfig.Register);
        }
    }
}
```

And my WebApiConfig.cs is:

```
using System.Web.Http;
using System.Web.Http.Cors;

namespace PharmiWebPortal
{
    public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            var corsAttr = new EnableCorsAttribute(RouteConst.AllowedDomains, "*", "*");
            config.EnableCors(corsAttr);
        }
    }
}
```

**Comment by nathanwoulfe** [comment]
First thing you could try is refactoring the event binding per https://our.umbraco.com/documentation/Reference/Events/Application-Startup. Might make a difference...

**Comment by nathanwoulfe** [comment]
Confirming that a clean Umbraco 7.13.2 with Plumber 1.1.4 installed via Nuget starts with no issues. Issue must be elsewhere in your implementation code, I'd start with refactoring the OnApplicationStarting event to an ApplicationEventHandler, implementing ApplicationStarted.

Will leave this issue open for now, but I don't believe there is any work required at my end.

**Comment by Asadlerpwcom** [comment]
I have refactored the code a few times now, with no luck.

It only breaks when i install this particular plugin.

I followed the instructions below on how to enable CORS, however i have tried it using all 3 of the application startup handlers with no luck.

https://our.umbraco.com/forum/umbraco-7/using-umbraco-7/63841-Web-API-2-and-cross-origin-resource-sharing-CORS#comment-226426
