### ISSUE TITLE
In some cases, the 'Request Publish' button does not swap to 'Save' after content edits are made

### ISSUE THREAD

**Issue by tomfulton** [nathanwoulfe/Plumber#101]
# In some cases, the 'Request Publish' button does not swap to 'Save' after content edits are made

### Background

When an editor makes a change and wants to request a publish, Plumber requires they explicitly perform a **Save** first.

Plumber makes this intuitive by making **Save** the default action when it detects a change occurred:

<p align="center">
<img src="https://user-images.githubusercontent.com/1396376/52506814-008ba880-2bad-11e9-9300-c8b37c39927a.gif" />
</p>

However, in some cases Plumber does not detect changes, and keeps the default action as **Request Publish**.

<p align="center">
<img src="https://user-images.githubusercontent.com/1396376/52506820-04b7c600-2bad-11e9-84e4-5e04cfd899ac.gif" />
</p>

If the editor clicks **Request Publish** in this case, their changes are not saved.

These cases seem to be specific to certain property editors - identified so far:  Content Picker, Slider, Media Picker, Date Picker.  

### Resolution

The source of the bug appears to be in the Umbraco Core, as these property editors do not seem to properly mark the form "dirty" when changes are made.  This also seems to cause Umbraco's "You have unsaved changes" warning to be ignored for these editors.

A simple fix might be to submit PRs to the Umbraco Core that correct these specific property editors, allowing Plumber's button-swap feature to work in all (?) cases.

One possible downside to this approach (on it's own) is that some 3rd-party property editors may have the same issue - it might be cumbersome to identify them all, and lead to potential confusion or lost edits for someone down the road.

Happy to take a look at creating the core PR if you think it's the best approach!

---

### Alternative UX?
While researching this, I wondered whether an alternative UX might help with the issue as well, and included some general ideas below.  These are probably not needed if the above resolution is implemented and Plumber's change detection can work reliably, but might be worth discussing as it seems Umbraco 8 is [moving in a different direction](https://twitter.com/marcemarc/status/1090972492917886977/photo/1) as well.  Though, I do like how Plumber's current UX helps prevent erroneous **Save** operations and helps guide the user.

#### Split out the Save button from the button group
To help get users more familiar with Saving first, one thought is to separate **Save** from the **Request Publish** button group, moving to it's own button that is always present.  It then might be easier to train users to click it first, without having to worry about whether the context of the default button changed was changed or not (e.g. "the green button never saves changes").

One issue here is that users could still opt to not click 'Save' and click the green 'Request Publish' first, but this could be avoided by making them context-sensitive (combined with the above resolution for change detection).

_Example:_

![save-button-separate](https://user-images.githubusercontent.com/1396376/52506808-f9fd3100-2bac-11e9-9be1-dc4695af2566.png)

#### Make 'Save' the default action
If it doesn't make sense to move 'Save' outside of the button group, another thought is to make it the default action instead of 'Request Publish'.  This is similar to the above in the sense that 'Save' is a distinct action that is always present, and makes it harder to confuse with the 'Request Publish' button.  It also has the same downside as above, that users could still bypass 'Save' inadvertently.

_Example:_
![save-button-default](https://user-images.githubusercontent.com/1396376/52506796-ece04200-2bac-11e9-98e9-38ddfed3a872.png)

#### Implement 'Save and Request Publish' button
The 'Request Publish' button could potentially be changed to a 'Save and Request Publish' button that performs both operations, similar to the default 'Save and Publish' button in Umbraco.  

_Example:_

![save-and-request](https://user-images.githubusercontent.com/1396376/52506803-f36eb980-2bac-11e9-810b-606127bae649.png)

**Comment by nathanwoulfe** [comment]
Firstly, your issue reports are magical.

I think I'd lean towards the final option and just perform the save internally. I'm hesitant to split the save button out of the button set pre-v8, I don't want to preempt any UI changes. Best benefit of the save+requestpublish button is it's the easiest change to implement, although I really like having the separate save button as it makes it easier to progressively save changes before requesting publish.

Could also simply change the behaviour of the request publish button to save if the model is dirty, but I can't remember if there's a mechanism for comparing the publish request to the published entity.

I think too that the core dirty checking should be fixed. If doing that then highlights other packages that need updating to do the same, then I don't see that as an issue from my end, it's something other package developers should resolve.

So all that said, probably a combination of the two - maybe showing the explicit save button when changes are detected, but with some logic in place to show save+request when appropriate. Not sure if that will then create unnecessary saves though.

Might throw it open on the Twitters too and see if any UI/UX experts feel like contributing...

**Comment by tomfulton** [comment]
Sounds great - I submitted umbraco/Umbraco-CMS#4491 to fix Media Picker, Slider, and Date Picker.  Content Picker was already fixed in a recent version.  

FYI, I also found an [already reported issue](https://github.com/umbraco/Umbraco-CMS/issues/4140) with the RTE where it wouldn't set dirty after an initial save, and addressed in umbraco/Umbraco-CMS#4492.  I wonder if there might be other edge cases out there as well, but one of these solutions will probably cover them.  

I'll have a think about the buttons too :+1:.  If we can rely on Umbraco's dirty checking with these fixes, I wonder if it even makes sense to add the internal save, since we'll always know the Save button would be available since the form is dirty?  Or would it make sense to add the internal save anyway, to cover any edge cases we're unsure about, unpatched Umbraco versions, etc?

**Comment by tomfulton** [comment]
Hi @nathanwoulfe,

I submitted a quick PR for 'Save and Request publish' as a potential solution for this issue.  All works the same, except when clicked, it'll perform a 'Save' before showing the 'Request publish' dialog.

I'm not sure if this is the ideal solution (unneeded save operations, extra notifications), but it seems like a simple way to fix this issue (including any remaining edge cases) and prevent data loss.

As an alternative, we could choose to trust Umbraco's dirty checking and keep today's behavior of presenting 'Save' when dirty, 'Request publish' when clean.  But, I'm not sure if there could be other issues out there (I did find [one](https://github.com/umbraco/Umbraco-CMS/issues/4140)), and they might not be easily discovered/supported since Umbraco doesn't (seem to?) rely heavily on the dirty checks — so perhaps this is the 'safest' solution for now.  Maybe there's a more robust way to check for "dirty" - e.g. comparing models as you said?

Appreciate any thoughts!

**Comment by nathanwoulfe** [comment]
Hi @tomfulton, that looks good to me. I'd like to avoid the extra save, but it's not really possible at the moment. V8 solves it by splitting out the save button, so all good once that hits the shelves.

**Comment by nathanwoulfe** [comment]
### [nathanwoulfe](/nathanwoulfe) added a commit that referenced this issue [ 2 hours from now ](#ref-commit-9080b94)
[ ](/nathanwoulfe)

I'm in the FUTURE!

**Comment by tomfulton** [comment]
Agreed - thanks so much! :+1:
