### ISSUE TITLE
Any plans for Umbraco 8

### ISSUE THREAD

**Issue by JoseMarcenaro** [nathanwoulfe/Plumber#104]
Hi Nathan,
great plugin!  Are there any plans to develop an Umbraco v8 version? Thanks!

**Comment by nathanwoulfe** [comment]
Hi Jose, a v8 version is underway, [repo is here](github.com/nathanwoulfe/plumber8). I wouldn't recommend using it on a production site, but I'll have a nightly build available in the next few days for testing and so on.

It's largely working, but I'm in a tricky spot where I want to focus solely on 8, but need to provide support for 7 too, for at least the next few months... Good times!

**Comment by JoseMarcenaro** [comment]
Hi Nathan, 
that's great. Thanks a lot!

**Comment by GFoley83** [comment]
Any update on this one Nathan? Is Umbraco 8 support any further along?

**Comment by nathanwoulfe** [comment]
Nearly done. There's a repo for Plumber 2 with the latest beta available on the releases tab. Has a few known issues that I'm working on.
