### ISSUE TITLE
Error - Could not get log dates : when upgraded from 7.13.2 to 7.15.2

### ISSUE THREAD

**Issue by hamzatki** [nathanwoulfe/Plumber#115]
Hi Nathan,

I am getting this error when i upgraded from umbraco 7.13.2 to 7.15.2 using Plumber 1.1.5

I am also getting the same error when I upgraded to Plumber 1.1.10

An error occured
Could not get log dates
Exception Details
NullReferenceException: Could not get log dates
Stacktrace
at Workflow.Api.LogsController.GetDateList()

Thanks for your help.

Kay

**Comment by nathanwoulfe** [comment]
Hi Kay, when you upgraded Umbraco, did you merge the Plumber-related config in /config/log4net.config?

https://github.com/nathanwoulfe/Plumber/blob/master/Workflow.Site/config/log4net.config has an appender and logger added for Plumber, if these were overwritten in the upgrade logging will be broken.
