### ISSUE TITLE
Publish button always available in "do something else" panel

### ISSUE THREAD

**Issue by willchis** [nathanwoulfe/Plumber#117]
Sorry to hit you with another issue, but it was something I noticed when testing some of your recent bug fixes!  Let me know if I can help in any way.

**Describe the bug**
The option to publish is always available to content editors in the "do something else" panel, therefore making it possible to bypass any approval flow.

**To Reproduce**
1. Log in as a content editor
2. Go to a page that needs to go through an approval flow before publishing is allowed
3. Make some changes to the content
4. Note that only the "Save and Request publish button is present (as it should be)
5. Right click on the node name in the content tree (or left-click it and then click the "Do something else" button.
6. The publish button is visible in the panel that pops out.
7. Click the publish button to publish the page without going through the approval flow.
8. Changes are published and appear on the site.

**Expected behavior**
Publish button should not be available in the pop out "do something else" panel if you are not an admin.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/3491130/64598243-4c0a6d00-d3af-11e9-8dcb-32667091a06c.PNG)

**System details:**
 - Umbraco cloud 7.15.3
 - Chrome browser

**Plumber version**
1.1.10 (and also seen in Plumber_1.1.10-alpha-000384 build)

**Comment by willchis** [comment]
Thinking about this a bit more, maybe publishing should just be turned off for content editors anyway (via the user group permissions), meaning that this isn't an issue after all?

![image](https://user-images.githubusercontent.com/3491130/64601199-68f56f00-d3b4-11e9-9dfc-42fee92121ae.png)

**Comment by nathanwoulfe** [comment]
Yup, that would be the preference - from memory, I tried removing the publish button from the context menu, but that caused other issues. Easiest and most robust way is to disable permissions
