### ISSUE TITLE
workflow.site - demo site address

### ISSUE THREAD

**Issue by lhall690** [nathanwoulfe/Plumber#122]
**Describe the bug**
What is the url for the demo site address please? - it does not appear in the documentation (although the login details do)

**Comment by nathanwoulfe** [comment]
Demo site doesn't exist any more, I need to update the docs to remove it. 

Instead, clone+build the repo - there's an Umbraco instance as part of the solution, same login details should work.

**Comment by lhall690** [comment]
Thanks Nathan – my main question I wanted to solve with the demo site was just what do the approvers actually see when reviewing  changes made by editors? Does it just rely on comments made inline? Or is there a highlight or something?


[cid:email-signature-logo_86d17f6c-911c-4e9c-b900-51ea644f0936.png]     Lewis Hall
Project Manager
Everest Media Ltd
p: 01872 300780
a: Pool Innovation Centre, Redruth TR15 3PL
w: www.everest-media.co.uk<https://www.everest-media.co.uk/?utm_source=email&utm_campaign=Hall_06012020_1009> e: lewis.hall@everest-media.co.uk<mailto:lewis.hall@everest-media.co.uk>
[cid:Facebook_2f2e5d45-1a71-4c0e-8b51-8aa6f2bb501b.png]<https://www.facebook.com/EverestMediaLtd/>  [cid:Twitter_b63988bc-7da8-4ccd-826a-3fd65bb5002a.png] <https://twitter.com/everestmedialtd>

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the sender immediately.

**Comment by nathanwoulfe** [comment]
Approvers see the comment submitted by the editor when they request the approval, so there's a reliance on the editor providing a decent explanation of their changes. 

Biggest difficulty with providing highlighted changes is the increasing number of JSON based property editors, so showing highlighted changes gets confusing real quick for non-technical users.

**Comment by lhall690** [comment]
Thanks Nathan! That’s what I thought, cheers for your help &#128522;


[cid:email-signature-logo_86d17f6c-911c-4e9c-b900-51ea644f0936.png]     Lewis Hall
Project Manager
Everest Media Ltd
p: 01872 300780
a: Pool Innovation Centre, Redruth TR15 3PL
w: www.everest-media.co.uk<https://www.everest-media.co.uk/?utm_source=email&utm_campaign=Hall_06012020_1407> e: lewis.hall@everest-media.co.uk<mailto:lewis.hall@everest-media.co.uk>
[cid:Facebook_2f2e5d45-1a71-4c0e-8b51-8aa6f2bb501b.png]<https://www.facebook.com/EverestMediaLtd/>  [cid:Twitter_b63988bc-7da8-4ccd-826a-3fd65bb5002a.png] <https://twitter.com/everestmedialtd>

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the sender immediately.
