### ISSUE TITLE
Notification settings per group

### ISSUE THREAD

**Issue by lhall690** [nathanwoulfe/Plumber#124]
**Is your feature request related to a problem? Please describe.**
One approver group would like their notifications turned off, but another would like them on - doh! 

**Describe the solution you'd like**
An option within each approver group to switch notifications on or off.

**Describe alternatives you've considered**
Turning notifications off for everyone and then adding some sort of alert when tasks have been in the approvers queue for a certain period of time.

**Comment by nathanwoulfe** [comment]
@lhall690 you can manage this with configuration - for the groups who don't want notifications, set the group email address to a generic inbox (or one you control, then use a rule to trash the emails). 

Emails go to individual users when the group address is not set, so you can use that as a filter...

**Comment by lhall690** [comment]
ah ok! yes good idea
Thanks
