### ISSUE TITLE
v7.15.5 Request Publish Notification Error

### ISSUE THREAD

**Issue by samtruedig** [nathanwoulfe/Plumber#135]
**Describe the bug**
With an approval process setup, when requesting publish a notification error "Workflow: Unable to request publish, saving the content failed" is always presented.

**To Reproduce**
1. Use Umbraco 7.15.5, issue not present in Umbraco 7.15.4.
2. Set up an approver group and approval flow for a content type
3. As an editor change an instance of that content type and select "Save and Request Publish"

**Expected behavior**
Request publish to complete and no error to be displayed

**Screenshots**
![_Local_Content_localhost](https://user-images.githubusercontent.com/52410463/85837225-af735900-b78f-11ea-8006-428be83dad7d.png)

**Desktop (please complete the following information):**
Windows 10 Chrome browser

**Plumber version**
Plumber version 1.1.11

**Additional context**

**Comment by nathanwoulfe** [comment]
Hi @samtruedig 

Slow reply, sorry. Will try to get to this.

**Comment by nathanwoulfe** [comment]
Resolved in latest.
