### ISSUE TITLE
JavaScript Errors in Console When Creating Approval Group

### ISSUE THREAD

**Issue by Nicholas-Westby** [nathanwoulfe/Plumber#14]
When creating an approval group, I get the JavaScript errors "section cannot be null" and "No childNodesUrl property found on the tree node, cannot load child nodes" in my Chrome console.

This prevents the creation of approval groups when "Approval groups" is selected. Also, it seems like the creation of approval groups fail otherwise (i.e., when I don't have "Approval groups" selected in the tree), but once I refresh the page I see the approval group.

**Comment by nathanwoulfe** [comment]
This should be resolved in 0.4.2 - I've revisited how I managed the routing for the workflow section. I'd tried to be a bit too clever, so reverted it back to the standard Umbraco format, which while it means duplicating segments (/workflow/workflow/action), it works, so must be a winner.

There's a few other bits and pieces in there, just tidying up smelly bits.

**Comment by Nicholas-Westby** [comment]
This appears to have been fixed. Closing.
