### ISSUE TITLE
Backoffice api issues after installing package (Umbraco cloud)

### ISSUE THREAD

**Issue by SRandomName** [nathanwoulfe/Plumber#143]
**Describe the bug**
We are unable to enter the Umbraco Cloud backoffice after installing the plumber package.

![image](https://user-images.githubusercontent.com/48089189/98561042-b4512900-22a8-11eb-8583-1b0d000f14dd.png)

**To Reproduce**
Fresh install of plumber package
deploy to umbraco cloud

**Plumber version**
Which version of Plumber does the bug occur in? v1.4.2

**Additional context**
Clearing cache/cookies doesn't fix the problem. Only deleting the plumber dll's fixes the problem.
Any ideas ? Thnx!

**Comment by nathanwoulfe** [comment]
Possibly related to using attribute routing, maybe perhaps. I haven't tested on cloud, but also haven't had any reported issues from cloud...

Does the site have any non-standard WebApi config?

**Comment by nathanwoulfe** [comment]
@SRandomName just realised this issue is related to Plumber on Umbraco 8 - this repository is for Plumber on Umbraco 7. Please create a new issue on https://github.com/nathanwoulfe/Plumber-2
