### ISSUE TITLE
Workflow Dashboard Sometimes Not Installed

### ISSUE THREAD

**Issue by Nicholas-Westby** [nathanwoulfe/Plumber#15]
I just installed Plumber 0.5.1 into a real Umbraco 7.7.9 website by installing the "Workflow.Umbraco" NuGet package.

One thing I noticed that was different from my test install is that no "Workflow" dashboard was installed in the content section. I was able to copy the relevant portion out of the `dashboard.config` of my test install to get it working, but odd it wasn't installed.

Two theories:

* Perhaps you are transforming the `dashboard.config` with XSLT that expects `StartupDashboardSection` to exist (I had that section commented out).
* Perhaps the NuGet install in particular doesn't modify the `dashboard.config`.

**Comment by nathanwoulfe** [comment]
You're correct with the first theory - I'm looking for StartupDashboardSection, then adding the tab markup.

Can go two ways - either I do nothing if that node doesn't exist (the current behaviour), or generate it and add it to the config. Only issue I see with the latter is that if it's not there, it has been removed for a reason, so I don't think it would be polite to add it back in...

Wonder if the better way to manage it would be to check for the StartupDashboardSection node, and if it doesn't exist, return a message as a post-install event or something similar.

**Comment by nathanwoulfe** [comment]
I've always just added to StartupDashboardSection as habit - didn't realise it wasn't necessary. Will update the installer to create a new section by default.

**Comment by nathanwoulfe** [comment]
Resolved in v0.5.2
