### ISSUE TITLE
Cannot install on Umbraco v.8.2.10

### ISSUE THREAD

**Issue by mrmjprice** [nathanwoulfe/Plumber#152]
**Describe the bug**
Could not install on Umbraco v.8.2.10

**To Reproduce**
1. Install using [Release .gzip from GitHub](https://github.com/nathanwoulfe/Plumber/releases/tag/v1.1.15)

```
Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.
```

<img width="1386" alt="Screenshot 2021-02-17 at 17 53 10" src="https://user-images.githubusercontent.com/10854265/108247026-0926fa00-714a-11eb-8b2e-884f178c99cb.png">

Reporting on behalf of @catiarodriguescosta

**Comment by nathanwoulfe** [comment]
Hi @mrmjprice, for v8 you'll be looking for Plumber2 - it's a nuget-only install:

`Install-Package Plumber.Workflow`
