### ISSUE TITLE
Please ensure a workflow has been set on the content nodes listed below bug

### ISSUE THREAD

**Issue by rasolo** [nathanwoulfe/Plumber#158]
**Describe the bug**
I get this message: "Please ensure a workflow has been set on the content nodes listed below: Startpage"
all the time even though I have added Startpage to content type approval flows with an assigned approval group.  The popup message keeps appearing all time time. It only goes away if I exclude the start page which I don't want to do because all the descendant pages will be removed from the workflow and they need to be included.

**To Reproduce**
Add the startpage to be in the content approval flows and the error message will appear, and also if it isn't assigned.

**Expected behavior**
The message should go away when the start page is defined in the approval flow with an approval group.

**Screenshots**
https://ibb.co/prBC5jR
(It complains about "Startsida" which is StartPage in english and you see startpage is already added to the right side

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome firefox edge
 - Version latest versions

**Plumber version**
1.1.15

**Additional context**
Umbraco 7.15.6

This bug is similar to https://our.umbraco.com/packages/backoffice-extensions/plumber-workflow-for-umbraco/plumber-workflow-for-umbraco-discussion-and-troubleshooting/95912-workflow-configuration-by-content-node

But it seems to have come back again, at least for me.

**Comment by nathanwoulfe** [comment]
Hey @rasolo do you have more than one node if the Startpge type? If not, try setting the workflow on the node rather than by content type. Even with more than one, it's probably worth trying just to see if it fixes the error.

**Comment by rasolo** [comment]
> 
> 
> Hey @rasolo do you have more than one node if the Startpge type? If not, try setting the workflow on the node rather than by content type. Even with more than one, it's probably worth trying just to see if it fixes the error.

Hey @nathanwoulfe, how do I do that? It looks like it only allows me to set by content type. There is only 1 startpage type

**Comment by rasolo** [comment]
Solved! I found where to do it. Go to the start page in this case and click on the top right "events" or whatever it's called in english and workflow configuration to set it for the start page and the message goes away.

Thanks!
