### ISSUE TITLE
Request Publish Button Doesn't Show Circular Spinner

### ISSUE THREAD

**Issue by Nicholas-Westby** [nathanwoulfe/Plumber#16]
In a normal Umbraco install, when I click "Save & Publish", I see a spinner on the button that stops spinning once the publish is complete.

The "Request publish" button seems to initiate a publish, but it doesn't have a spinner. That's problematic on the site I'm currently working on, as the publish operation takes like 10 seconds, so the user doesn't get feedback during that time.

I know, 10 seconds is a long time, but it's not a typical site (it generates static files for the entire site on publish).

Umbraco 7.7.9. Workflow.Umbraco/Plumber 0.5.1.

**Comment by nathanwoulfe** [comment]
Yup, should be easily fixed - I never set the state attribute on my button group.

**Comment by nathanwoulfe** [comment]
Give v0.5.2 a spin - has spinners back for button actions.

**Comment by Nicholas-Westby** [comment]
Looks good, so I'll close this ticket.

I did notice some oddities when clicking a button that's in the drop down, but Umbraco might just normally do that. I'll do some more testing and submit a ticket if I find anything.
