### ISSUE TITLE
Crashes when trying the demo site

### ISSUE THREAD

**Issue by Spudley** [nathanwoulfe/Plumber#2]
Hi.

I was interested in trying out your workflow plugin for Umbraco; it sounds like exactly the kind of thing I'm looking for.

However when I tried logging into the admin panel on your demo site (as TestUserA), I just got an endless stream of "Oh Snap" error messages scrolling past faster than I could even read what they said.

ps - I found out about it [on a thread at our.umbraco](https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/64823-Does-Umbraco-7-support-approval-workflow-out-of-the-box).

**Comment by nathanwoulfe** [comment]
Yeah, that shouldn't be happening... Looking into it now.

**Comment by nathanwoulfe** [comment]
Should be working again now - looks like there was an issue with a concurrent write to the database (I think), probably partially related to using SQLCE. Ended up with a corrupt workflow instance, deleting it solved the problem.

Will need to look into what exactly happened, and also suppress the multiple notifications - looks like the request is being resent when the error returns, causing the infinite notifications loop.

Let me know if you have any other issues...

**Comment by Spudley** [comment]
Thanks. All sorted  :)  I'll have a play around with it.
