### ISSUE TITLE
Plumber 0.7.4 patch has console errors and somtimes issue occurs for final stage approve

### ISSUE THREAD

**Issue by pyajamanam** [nathanwoulfe/Plumber#27]
Hi Nathan,
@nathanwoulfe 
When i initiate workflow from authors when i click on request to publish below error was displaying.

Also i have a doubt ex U1 is at stage 1 to approve , so do i need to give send to publish from groups section else It will automatically will override the existing permissions present in the work flow.

Ex: U1 ->group only update,publish if the U1 in workflow will this be allowed to send for approval or directly will publish.
![wf3](https://user-images.githubusercontent.com/33079424/37287922-f3f2a7cc-262b-11e8-88c9-f88a8a30fcf9.PNG)
![wf5](https://user-images.githubusercontent.com/33079424/37287928-f950e74c-262b-11e8-82f2-f8dcf2384722.PNG)

Thanks,
Pradeep

**Comment by nathanwoulfe** [comment]
Hi Pradeep

I can't reproduce either of these - the javascript error is related to a change made several versions ago. There might be old files in your app_plugins/workflow folder?

I've tested the workflow process, and can't reproduce the sql error. There's no need to modify default user permissions to configure Plumber, so long as the user has access to edit the node, publishing is then managed by Plumber. If they have browse-only, the user is shown the default Umbraco buttons.

I'll update my local site to 7.9 and test it again. If you could provide more detail around how you've set up your site that would be helpful too.

N

**Comment by nathanwoulfe** [comment]
If you want to try modifying the umbEditorFooterContentRight.html partial, delete at line 44:

`state="vm.buttonGroup.state || 'init'"`

The javascript is up to date. Somewhere along the line the html has been missed.

**Comment by pyajamanam** [comment]
Hi Nathan,
I have verified this issue again.
1. If the workflow is in final stage,
And user approves to publish with,the button remains as is so that the again if the user clicks on approve it will produce error in  tasks controller when there is not instance for it.
Updated the issue in detail in below 
https://our.umbraco.org/projects/backoffice-extensions/plumber-workflow-for-umbraco/plumber-workflow-for-umbraco-discussion-and-troubleshooting/91047-upgrading-umbraco-version-792-with-plumber-package-getting-issue

**Comment by pyajamanam** [comment]
If I approve in final stage it will get published. And again the approve button shows so if I click again it will throw error.

**Comment by nathanwoulfe** [comment]
I think I've found why - looks like a bit of a race condition where the check for changes on the page returns before the buttons have been set, and shows the request publish rather than approve changes.

**Comment by pyajamanam** [comment]
Also is there any possibility to reset all workflow clearing junk from tables and start configured again..
Are you getting errors in console ?

**Comment by nathanwoulfe** [comment]
There's not, at the moment - if it would be useful, just create an issue and I'll include it in a coming release. Wouldn't be a huge task.

**Comment by nathanwoulfe** [comment]
Can you please try the attached - rename to workflow.js and replace the file currently at app_plugins/workflow/backoffice/js. Once we can verify this fixes the issue, I'll build.

[workflow.txt](https://github.com/nathanwoulfe/Plumber/files/1805480/workflow.txt)

**Comment by pyajamanam** [comment]
Sure  I will do it.. and create issue as well

**Comment by nathanwoulfe** [comment]
That's odd, it shouldn't be - the context menu is only bound to content items with an id > 0, so should never fire in the recycle bin. Will look into it.

Good to see the javascript change fixes the problem - I added an additional call into the function responsible for setting the visible button. Previously it was running, but then being overwritten by the check for the user permissions on the node. I've made that second check then call back into the first function, if a workflow is active, to ensure the buttons are set correctly.

I'll push out a build tonight with that change, and anything else related to the recycle bin, if anything turns up.

**Comment by pyajamanam** [comment]
Hi Nathan, did you get a change to look into new version of Umbraco.
How can I deploy the source code.
DLL and applugin is enough or do I need to add any other things. Grunt file ,package.json

**Comment by pyajamanam** [comment]
Hi Nathan, did you get a change to look into new version of Umbraco.
How can I deploy the source code.
DLL and applugin is enough or do I need to add any other things. Grunt file ,package.json

**Comment by nathanwoulfe** [comment]
Don't deploy the source code - download and install the compiled package from appveyor or install via nuget.

I'm running it on 7.9.2 and haven't seen that error.

**Comment by pyajamanam** [comment]
to reproduce this issue click on approve changes and after approved do cancel workflow. again approve changes. you can see the same issue again.

error source is    public IHttpActionResult GetNodePendingTasks(int id) in this going to try the instance and exception thrown.
this issue will come once approve button complete still button available so by clicking approve again it shows issues
![wf7](https://user-images.githubusercontent.com/33079424/37341819-d35fd756-26e8-11e8-8d60-4e36a7afe4cf.PNG)

this issue will come in the approval flow which has no instance.

![wf8](https://user-images.githubusercontent.com/33079424/37341835-dfcf14d4-26e8-11e8-8ea0-bff889f0becc.PNG)

**Comment by pyajamanam** [comment]
please let me know which one is using am still able to see this first drop down 

![flow1](https://user-images.githubusercontent.com/33079424/37342669-4797c424-26eb-11e8-83ff-e718e94fabfa.PNG)

is this is a issue 
![flow2](https://user-images.githubusercontent.com/33079424/37342675-4b732c96-26eb-11e8-8b46-9f6b93611dce.PNG)

please let me know the differences.

**Comment by pyajamanam** [comment]
Hi Nathan,
Could you please try doing approve changes then cancel workflow and do request to publish in the second stage of workflow.
You can see the issue

**Comment by nathanwoulfe** [comment]
If you cancel the workflow, how are you then requesting publish in stage 2? You'll be starting a new process since you cancelled the previous one.

**Comment by pyajamanam** [comment]
Please try to do like this.
U1 is the first one who will start request to publish,
U1 permissions are browse node,save.
2.once u1 request to publish it will be submitted to stage 2 approval. Here in stage 2 U2 will edit changes and able to see save option and then request to publish.
So it will sent back to u1(correct me if am wrong)
Then when u1 approves it publish directly.

The error which I was getting is when U2 approves it was showing error in getnodetasks.
Also in the final stage of u3 I have set only browse node and save so. That u3 will publish once all the group's approve ignore u1.
Note:the issue am getting is when I do save and request to publish to next stage or previous stage.
Please let me know if you need more info on this

**Comment by nathanwoulfe** [comment]
Changes in stage 2 will not be sent back to stage 1, the workflow will progress to the next stage.
If a user can only browse the node, they won't see the workflow buttons. So long as they can save, it doesn't matter whether they can publish as the package does it directly.

I'll try to replicate.

**Comment by pyajamanam** [comment]
Could you please let me know I have scenario of u1,U2,u3
When u1 will initiate and ends at u3.
In between U2 will add changes again will this be considered to next stage.
Also I have selected drop-down as all groups approve ignore author.
Can I know the exact config settings to work as expected.

**Comment by nathanwoulfe** [comment]
u2 will not be able to modify - once the workflow is active, the content is locked.
Are you running the code from the repo or the package? If you've set ignore author, all groups will have to approve the change but the original change author will be excluded from email notifications.

**Comment by pyajamanam** [comment]
So in this case if I want to complete the flow from u1 to u3 all the users with browse node permission is enough?
2.once the flow completed u3 will do some changes,and will it falls back to default approval group or original author?
3.how can I add additional changes in the middle from U2 perspective and see the changes with u1+U2 as well

**Comment by nathanwoulfe** [comment]
Once a workflow is completed the content can be edited like normal, and submitted into a new workflow process. It will go back to the first approval group.

Changes cannot be added during a workflow without rejecting the task and having it assigned back to the original author. Once the item is resubmitted, it will go back to the workflow stage where it was rejected.

**Comment by pyajamanam** [comment]
Thanks for your response,when would be the default approval group will be used.

**Comment by nathanwoulfe** [comment]
Will only fall back to the default group if nothing is set anywhere else ie no workflow set on the hompage node.

**Comment by pyajamanam** [comment]
How to disable user without using workflow.
 I.e it should work as it is as CMS please publish mechanism.it should not show workflow in the bottom of the page..

**Comment by nathanwoulfe** [comment]
Yup, exclude node will fallback to the Umbraco default permissions for that user. This setting cascades, so will apply to the selected node and all descendents

**Comment by pyajamanam** [comment]
Hi Nathan,
just now i have integrated the latest build of 0.7.4.152,i can see the changes of css.
but on click of history it will throw null exception,and also flow type coming as explicit and implicit.is this is a new change in drop-down.
![wf11](https://user-images.githubusercontent.com/33079424/37385184-ef3af394-2778-11e8-99a7-46c63dca8a58.PNG)

![wf10](https://user-images.githubusercontent.com/33079424/37385140-b361ac50-2778-11e8-9b75-0ed0864b0925.PNG)

**Comment by nathanwoulfe** [comment]
Explicit/implicit is correct, I'd been intending to replace the old options because they weren't really useful. 

Wondering if the previous issues you had have resulted in corrupted entries in the database... I'll have a look at the history issue, but have a feeling it's going to be a data issue

**Comment by pyajamanam** [comment]
I feel by switching versions and data maybe not working properly.
could you please check and confirm with new patch so that i will download it and test thoroughly.
or else can i empty all the workflow tables data once.
is that fine.

**Comment by nathanwoulfe** [comment]
I agree - likely that some of those process that allowed you to submit 4 times in a 3 step workflow might be responsible.

Either have a look in the database for odd entries, or just delete the rows in WorkflowInstance and WorkflowTaskInstance tables. Should be fine to keep the settings, groups and user data.

**Comment by pyajamanam** [comment]
Hi Nathan,
I have  Cleared workflowInstance table and started from beginning.
still in the final stage approval changes button will appear after one time  click , so second time need to be disabled 
![wf7](https://user-images.githubusercontent.com/33079424/37404602-589b22e8-27b8-11e8-8a18-c7da3349831b.PNG)
which will returns exception.

if i refresh it button will be not be shown which is expected.
please verify from your side and let me know if this is issue.

**Comment by pyajamanam** [comment]
Hi Nathan,
There was an issue in workflow rejection changes.
Implicit scenario:
user initiates workflow request to publish.
user2 reject the changes and roll back to user1
now user1 resubmit the changes and requesttoppublish.
user2 approves the changes and it will show stage 3of3 changes
now user2 will have option to approve again once approve it will show stage4of 3
(here is the issue)
also one more user2 is allowed to approve multiple times which will be the issue i guess.correct me if am wrong.
![wf3](https://user-images.githubusercontent.com/33079424/40838689-f342dace-65bc-11e8-80a5-c05271f3483e.PNG)
![wf4](https://user-images.githubusercontent.com/33079424/40838690-f38782e6-65bc-11e8-9dff-48badf913304.PNG)

**Comment by nathanwoulfe** [comment]
What version are you running? This should be a new issue, not added to an unrelated closed one.

**Comment by nathanwoulfe** [comment]
looks like a sorting issue on the tasks collection, so the incorrect task is being updated when rejected. will sort it out today.

**Comment by nathanwoulfe** [comment]
building now with a fix - not in a release, so will need to grab the package from CI and install manually over your existing install. Might see some oddities on open workflows, but should be tested against new processes only.

Problem was caused by the sorting on the process tasks, where a stage with multiple tasks (ie multiple rejections) took the wrong task on re-submitting.

https://ci.appveyor.com/project/nathanwoulfe/umbracoworkflow/build/artifacts

**Comment by nathanwoulfe** [comment]
Or try v0.8.1 on NuGet. If the bug remains, please open a new issue
