### ISSUE TITLE
Debug from source code it will works in Local but Install local packages causes error 

### ISSUE THREAD

**Issue by pyajamanam** [nathanwoulfe/Plumber#28]
Hi Nathan,

i can see it very clear that when  i debug from source code it will works without errors but only small issue with final stage refresh not happening.

to reproduce : click U3 as approve in third stage(final stage) and able to publish the content and still button remains same as approve changes.
when page refresh it vanishes.

![enter image description here][1]

also let me know how can i push the source code to server environment.
Installing by local didn't work.
Please suggest me on this.

![wf7](https://user-images.githubusercontent.com/33079424/37332904-f0ffd68c-26cd-11e8-8601-cd874e06e2e2.PNG)

**Comment by nathanwoulfe** [comment]
I think you've got a mix of source and packaged code running - I'd delete everything in app_plugins/workflow and the workflow DLL, then reinstall from the latest build:

https://ci.appveyor.com/project/nathanwoulfe/umbracoworkflow/build/0.7.4.151/artifacts

This refactors the editor drawer buttons to use a more robust pub/sub pattern for determining the button type to display.

Remember too this package is still in beta, so will likely still have issues and probably shouldn't be used on a production site unless you're happy to be updating regularly and/or exposing users to bugs.

**Comment by pyajamanam** [comment]
Hi Nathan,
Thanks for responding back
 final stage approval button issue fixed regarding approve buton issue appears to submit multiple times.

**Comment by pyajamanam** [comment]
Hi Nathan,

just got small issue in publishing node.
below is the scenario followed
1st loop:
1.user2 approved changes 
2.user3 final approves reject changes.
3.user2 will get notified and resubmit changes.

2nd loop:
again user2 submit changes to user3 
 user 3 will reject changes once it clicked 
below is the error.

![55707bcc295b4c0f32f438c6bb46d42fd9d150be57fcaa69d4 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/33079424/40653396-a7fefaae-6358-11e8-86c3-79477e69b85a.png)
![86dc105f94699f8e35b4819be497c27569cad5cdd4c6338701 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/33079424/40653440-c68f8e3e-6358-11e8-94c6-086c35381684.jpg)

**Comment by nathanwoulfe** [comment]
yup, that's a bug - multiple rejections aren't working. found why, just dealing with it.

**Comment by nathanwoulfe** [comment]
building v0.8.0-beta now, this issue has been resolved.
build includes a fair few other changes, so let me know if anything isn't working - mainly UI changes, the workflow process itself is untouched other than the rejection fix.

**Comment by pyajamanam** [comment]
Hi Nathan,

could you please let me know the purpose of RTP and approve changes both when explicit is used.
this is when workflow initiated first user.
i am little confused on this.
Thanks,Pradeep
