### ISSUE TITLE
Only a handful of doctypes is showing.

### ISSUE THREAD

**Issue by rasmusfjord** [nathanwoulfe/Plumber#29]
I wanted to test plumber and im pretty impressed :)

I installed newest umbraco 7.9.2 and latest Plumber, together with the latest Umbraco starter kit. It only shows 5 doctypes to select from. I tried creating a new but that one dosnt show up either.

**Comment by rasmusfjord** [comment]
![image](https://user-images.githubusercontent.com/1286043/37347439-205da054-26d2-11e8-9da1-74e8976e1443.png)

**Comment by nathanwoulfe** [comment]
That's bad UX on my part - if you use the search input, it should filter the list. I'm updating the UI for the settings dashboard in the next release, and will be managing doctypes with a dialog. 

Working on some issues with the button state in the drawer on content items too, you'll probably notice it doesn't always update correctly

**Comment by rasmusfjord** [comment]
Hey Nathan 

Arh okay that makes sense, but its an awesome package, a few things i noticed, i dont know if it is a bug. I created a new user with editor rights, and added him to a workflow group. The save/publish dialog had both Umbracos and your request buttons in the dialog.

Med venlig hilsen

-----------------------------------------------
Rasmus Lykke Fjord
42 40 76 20
På 13-03-2018 19:46:20, Nathan Woulfe <notifications@github.com> skrev:
That's bad UX on my part - if you use the search input, it should filter the list. I'm updating the UI for the settings dashboard in the next release, and will be managing doctypes with a dialog.
Working on some issues with the button state in the drawer on content items too, you'll probably notice it doesn't always update correctly

**Comment by nathanwoulfe** [comment]
That doesn't sound right... Definitely shouldn't be seeing that! I'll look into it.

**Comment by rasmusfjord** [comment]
Roger, I thought it was intended so i went into users and removed the publish rights on the editor user group.

Med venlig hilsen

-----------------------------------------------
Rasmus Lykke Fjord
42 40 76 20
På 14-03-2018 11:02:51, Nathan Woulfe <notifications@github.com> skrev:
That doesn't sound right... Definitely shouldn't be seeing that! I'll look into it.

**Comment by nathanwoulfe** [comment]
Been having a fiddle with users and permissions, haven't been able to recreate this one - if you can give me a detailed rundown of how you'd set things up, I'll keep trying. The only group permission that Plumber cares about is Update - if a user can't update the node, they can't submit into the workflow. They can approve, but not initiate. Publishing is managed by the package, so user/group publishing permissions don't matter.

**Comment by nathanwoulfe** [comment]
build 0.7.4.159 is a revision of the doctype settings to a UI matching the normal node preview list. Only bit I'm not entirely happy with is having to choose the doctype, then edit the approval flow in a separate overlay. 

It's not a release yet, but is available on appveyor if you want to install and have a look.

https://ci.appveyor.com/api/buildjobs/jkay51ca1agsu5hs/artifacts/BuildPackage%2Fartifacts%2FPlumber_0.7.4-beta-000159.zip

**Comment by nathanwoulfe** [comment]
UI resolved in 0.7.5
