### ISSUE TITLE
Plumber 0.7.8: Is not possible to add group.

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#39]
With 0.7.8, I'm not able to add new group. If I click OK, nothing happen.

![image](https://user-images.githubusercontent.com/661517/39527553-fcc26734-4e21-11e8-9268-c67a9c875ce3.png)

**Comment by biapar** [comment]
Problem only on Chrome.

**Comment by nathanwoulfe** [comment]
Have tested a clean install of 0.7.8 on Chrome 65, works fine.
