### ISSUE TITLE
Save Group - issue

### ISSUE THREAD

**Issue by blevai13** [nathanwoulfe/Plumber#4]
Hi @nathanwoulfe 

There is a little issue in the Settings side, that I just discovered. When you go in the Workflow Settings in Approval Groups and made some changes there after you hit the save Group button when you want to go to another place like Content directly there is a message that pops up telling me that I didn't save the content(this message is the default umbraco behavior when you edit the content and didn't save it) and if I want discard the changes either want to stay. I think some service needs to be notified in umbraco services to let them know we saved and can move forward.

Thanks,
Botond

**Comment by nathanwoulfe** [comment]
Yup, that needs fixing. Need to set the form to pristine when the save resolves. Thanks for the heads-up

**Comment by nathanwoulfe** [comment]
This has been resolved

**Comment by blevai13** [comment]
Hi @nathanwoulfe 
First of all I want to say Thank you, for the fast reaction. The only thing I should notice here, that now that message with Discard Changes or Stay appears now when you are editing a content page. Hit the save button and then send the request, submit approval request and when you want to move from this content the message appears.
I think it might be affected that side when you took out the umbraco validation.

Thanks,
Botond

**Comment by nathanwoulfe** [comment]
That's likely caused by the same issue, the content form is being dirtied somewhere. The console message is unrelated to this issue, that's come from the other change made yesterday. 

Will sort 'em out.

**Comment by blevai13** [comment]
Yeah,
I found out that the user variable from controller has the same name the parameter from checkuserAccess and actually the variable from controller doesn't get assigned the new value. Renaming in the userservice     userService.getCurrentUser()
            .then(function (userResp) {... solves the problem with the error message.
And I also noticed that when I start writing the submission message on request approval gets the newValue true and the watcher sets dirty on true.
I hope this helps you!

Thanks

**Comment by nathanwoulfe** [comment]
Feels a bit dirty, but I've simply set the contentform to pristine after the workflow action requests. Also renamed the userservice response param, and found that the main dashboard wasn't updating when actioning tasks, so fixed that as well.

All built, should be good to go. Appreciate your feedback too, really useful having someone else looking at the bits I've overlooked!

**Comment by blevai13** [comment]
Excellent! Thanks and I'm happy to help you!

**Comment by blevai13** [comment]
Ok, this message doesn't want to disappear, now on the dashboard if you change a request(Cancel or Approve) and change the tab, tells me Discard changes... :)

**Comment by nathanwoulfe** [comment]
Should be good now - added noDirtyCheck directive to the comment field in the dialog. Adding a comment was dirtying the parent contentForm, didn't realise the child scope in the dialog would bubble to the parent form. Live and learn!
