### ISSUE TITLE
Where is the Workflow tab?

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#41]
Where is the Workflow tab?

![image](https://user-images.githubusercontent.com/661517/39564316-f73275d8-4eb3-11e8-92cf-116b21975292.png)

**Comment by nathanwoulfe** [comment]
I don't know. Check the dashboards.config file and ensure the dashboard is registered.

```
<section alias="WorkflowContentDashboardSection">
    <access>
      <deny>translator</deny>
    </access>
    <areas>
      <area>content</area>
    </areas>
    <tab caption="Workflow">
      <control addPanel="true" panelCaption="">/app_plugins/workflow/backoffice/views/workflow.userdashboard.html</control>
    </tab>
  </section>
```

On the off chance your user is a Translator, they won't be seeing it.

**Comment by biapar** [comment]
![image](https://user-images.githubusercontent.com/661517/39577304-3e545b70-4ee1-11e8-9503-1d766503ee72.png)
