### ISSUE TITLE
Content type approval flows not saved

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#42]
I try to save the content type approval flows, but always is empty.
Umbraco version 7.10.4 + Plumber 0.7.8RC
![image](https://user-images.githubusercontent.com/661517/39623303-7cb2e850-4f95-11e8-88db-bb4bb031f701.png)
![image](https://user-images.githubusercontent.com/661517/39623328-91d6e844-4f95-11e8-9c9d-332559b7ec02.png)

**Comment by nathanwoulfe** [comment]
After adding the content type, you'll need to edit the flow for that type (edit link on the right), to set the appropriate groups. It's not the best UX, will look at how I can improve it.

Have verified though that it saves correctly when the newly added type has had approval groups added.

**Comment by biapar** [comment]
I tried to add group from content, but don't work.
