### ISSUE TITLE
Workflow Configuration Incomplete: ensure a default approval group has been set.

### ISSUE THREAD

**Issue by JoseMarcenaro** [nathanwoulfe/Plumber#44]
Great work with this package! Thanks!

Small issue: although it looks like the Default Approval Group has been removed from the Settings and the docs, the Workflow Configuration action in drawer still reports the warning mentioned in the title.

I'm using a fresh install of the package v0.7.9.

Thanks,
Jose

**Comment by nathanwoulfe** [comment]
Cheers Jose!

Should be ok to ignore that message, I think. Will tidy it up today and get a release out.
