### ISSUE TITLE
Custom DataTypes not saved?

### ISSUE THREAD

**Issue by JoseMarcenaro** [nathanwoulfe/Plumber#45]
Hi Nathan
Unless I'm doing something wrong - entirely possible - it looks like some extended or custom data types do not get saved with Plumber save button, i.e.

- Nested Content
- Vorto
- nuPickers

If that is in fact missing for now, and custom code needs to be added for each of those property editors, can you point me in the right direction about where to implement them - and eventually submit a PR?
Thanks!

**Comment by nathanwoulfe** [comment]
You're right - the save for a page with nested content doesn't update the nested content property.
