### ISSUE TITLE
Workflow configuration is not saved

### ISSUE THREAD

**Issue by JoseMarcenaro** [nathanwoulfe/Plumber#46]
Hi Nathan

This may be related to the changes in #45 , but I'm opening a separate issue because it's a different problem.

I rolled back my website (database, folders, everything) to my original installation - Umbraco 7.10.4 without Plumber.
I then installed the latest build https://ci.appveyor.com/api/buildjobs/xxrdy8a1o6v4lump/artifacts/BuildPackage%2Fartifacts%2FPlumber_0.7.10-rc-000210.zip and configured an approval group

When I try to configure the workflow in any node, it looks like the configuration is saved:

![image](https://user-images.githubusercontent.com/923289/40056590-3c684e4e-5822-11e8-8ac7-bfccbb2e3460.png)

... and after clicking OK

![image](https://user-images.githubusercontent.com/923289/40056604-4c947414-5822-11e8-8aa3-d90dd973f1b3.png)

In fact, while I remain in that same node, the button behaves as when a workflow is active (Save => Request Publish).

But when I move to a child node and check the configuration, no workflow is inherited. And when I go back to the parent, the workflow configuration is gone - and the button reverted to the default Umbraco    options.

UPDATE: by "gone" I mean that the "Workflow configuration" action is still in the node drawer, but the configuration is empty - no content approval flow.

**Comment by nathanwoulfe** [comment]
I'd say that's a javascript issue - I made fairly substantial changes in that build, but was happy it was working correctly. Obviously isn't. 

Can you check the browser console for any js errors?

**Comment by JoseMarcenaro** [comment]
I did not have any Exclude nodes defined.  
Looking at this, I added a node and the error described in this ticket no longer happens.

Probably you should check for null anyway... but it solved my issue.
Thanks

**Comment by nathanwoulfe** [comment]
Excellent, thanks for digging. I'll patch that today.

**Comment by nathanwoulfe** [comment]
Latest build should sort this - returns false when excludedNodes is null, so no more error.
