### ISSUE TITLE
Publish Button

### ISSUE THREAD

**Issue by blevai13** [nathanwoulfe/Plumber#5]
Hi @nathanwoulfe,

I would have a question related to the umbraco default Publish Button, when we install the plumber workflow plugin, all users can see only the preview and save(or Request to Publish) buttons, which are fine and work, but also for users who has superior privileges would be nice to have this default publish button available too, in the right down corner as umbraco generally has. I mean, now, for example if a user want to publish a document after he save it he needs to go the Action dropdown button and select from there the publish options, so this functionality is available with the workflow configuration too, but would be nice to show this publish button by default for users who can still publish the current document.
Is that makes sense for you?

Thanks,
Botond

**Comment by nathanwoulfe** [comment]
@blevai13, that makes perfect sense - I actually thought I'd done this already, obviously not.

**Comment by blevai13** [comment]
Hi @nathanwoulfe , 
Can you please give me an estimate on this when this changes will be committed? Thanks

**Comment by nathanwoulfe** [comment]
@blevai13, there's a [new package build available](https://ci.appveyor.com/project/nathanwoulfe/umbracoworkflow/build/0.1.0.55/artifacts), users should now get their default action button in the popup menu in the bottom toolbar. I've kept the request publish as the default, which changes to save when the content is dirty, but the default for the user, if it is save and publish, will be in the sub-menu.
