### ISSUE TITLE
Emails from razor templates

### ISSUE THREAD

**Issue by nathanwoulfe** [nathanwoulfe/Plumber#52]
TODO -> add email generation from cshtml files, to allow customising the system notifications.

https://harveywilliams.net/blog/rendering-mvc-emails-with-cshtml is a good starting point for parsing the razor into a string. Would need to add a UI to allow setting the fields for inclusion in the email, determined by the available fields on the group and instance models. Any properties on those should be able to be included in the email, using curly braces or something:

{{group.name}} {{user.name}} {{instance.node.name}} etc...

Could then allow markup in the email for branding etc. Razor template example included in forms is useful too.

**Comment by Matthew-Wise** [comment]
https://github.com/andrewdavey/postal 

Allows strongly typed models to be passed to a razor view for emailing. Hope this helps in some small way with an awesome package.

**Comment by nathanwoulfe** [comment]
That's pretty slick - would do everything I need. I think this might have been suggested in another issue too...

**Comment by biapar** [comment]
This is the issue: https://github.com/nathanwoulfe/Plumber/issues/70
