### ISSUE TITLE
Demo site issues

### ISSUE THREAD

**Issue by rosss-WilsonGL** [nathanwoulfe/Plumber#54]
Hey,
 
I tried cloning the repo and launching the demo site but there are a few issues with it. I think that they config files are missing. The config folder is still part of the csproj so it shows up in my VS but the actual files don't exist.  This then causes the error:

Configuration Error
Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately. 

Parser Error Message: Unable to open configSource file 'config\umbracoSettings.config'.

 `Line 21:     </sectionGroup></configSections>
Line 22:   <umbracoConfiguration>
Line 23:     <settings configSource="config\umbracoSettings.config" />
Line 24:     <BaseRestExtensions configSource="config\BaseRestExtensions.config" />
Line 25:     <FileSystemProviders configSource="config\FileSystemProviders.config" />`

Also the demos site login appears to be out of date. Took a look at the db file and there is no such user.

Thanks

**Comment by nathanwoulfe** [comment]
Been a long time since I've started the demo site from a freshly cloned repo, not surprised there are issues. Will look into it.

**Comment by rosss-WilsonGL** [comment]
Great thanks, got the site up and running.
