### ISSUE TITLE
Bulk Add Doctypes to workflows

### ISSUE THREAD

**Issue by loudambiance** [nathanwoulfe/Plumber#58]
We are setting up a new site, that has approximately 40 doctypes that will all be on the same workflow. It would extremely helpful if there was a way to add them all to the same approval process in one go, instead of having to do them one at a time.

**Comment by nathanwoulfe** [comment]
Apologies for the slow reply... This is probably achievable, and without (I think) too much effort. Will have a look, and possibly include in v0.9

**Comment by nathanwoulfe** [comment]
Latest build should solve this for you - https://ci.appveyor.com/api/buildjobs/yys9687s7n288q68/artifacts/BuildPackage%2Fartifacts%2FPlumber_0.9.0-beta-000263.zip

You'll be able to assign workflows to multiple content types in one pass, but won't be able to edit multiple - might try and get that working too...

Let me know if this works, or if you find any issues with the build.

**Comment by loudambiance** [comment]
This worked perfectly. I wanted to thank you for adding in this feature.
