### ISSUE TITLE
DocumentType Approval

### ISSUE THREAD

**Issue by blevai13** [nathanwoulfe/Plumber#6]
Hi @nathanwoulfe,
I'm digging in this plugin deeper and deeper so sorry if I flood you with these comments, but I also noticed if I set a group of approvals by document type this is not going to work in sense that on the label tells me(after I choose workflow configuration on a node) <Approval flow can be set by content type - this flow takes priority over any inherited flow.> but this groups doesn't get notified if I have set something for the current flow, would be nice that this approval option by content type would take priority over anything else set on the node. 
Here is my scenario what I want to achieve and maybe you will understand it better.
I have a Home Page in the root(backoffice)  and I want for this particular node to have a separate group of approvals, but also in the same time I want to define a General Approval Groups for the child nodes,  with the current functionality I could set both, but the content-type group of approvals doesnt get notified.
We would love to make this because we don't have to go over each child node and set the current flow, would be much more convenient to set on root node and the inheritance will do the work and in the same time we would have a separate group that approves the Home page(root).

So this is the only thing, that would be nice to have - if I set any group on content type in workflow settings that/those group should be taken place for that content type. I'm not sure if this could be achieved or it just too complicated. 
Let me know your thoughts!

And another bug, once I inserted a group for a node and hit ok, if I want to take that group out from the node and jus leave it empty the current flow, it doesn't allow me to save, in terms on clicking Ok nothing happens, but if I add back any group it will do the save.

Thanks,
Botond

**Comment by nathanwoulfe** [comment]
Not sure I understand what you're trying to achieve, or maybe the UI isn't clear enough. The workflow will recurse up the tree until it finds a node with a valid setting, then in cases where a node has more than one option set (ie has a doctype flow, and an explicitly set flow), the doctype flow will take precedence.

I'm reading your example as setting a homepage doctype flow, and a general approval flow on the hompage, and having the latter inherited by child nodes? I haven't built it to work this way, but that's not to say it isn't possible, or a good idea. 

I'll open a separate issue for removing the workflow settings for a node.

**Comment by blevai13** [comment]
Yeah, I see you but I think there is might a bug in the code, it supposed to work like you described, but I think for this code snippet it's not gonna work because we should use contentTypeApproval not approvalGroup here:

  var contentTypeApproval = _pr.PermissionsForNode(nodeId, instance.Node.ContentType.Id).Where(g => g.ContentTypeId != 0).ToList();
                    if (contentTypeApproval.Any())
                    {
                        group = **approvalGroup**.Where(g => g.Permission == taskInstance.ApprovalStep).First();
                        SetInstanceTotalSteps(approvalGroup.Count);
                    }

**Comment by nathanwoulfe** [comment]
That makes sense - have made this change in the latest build, let me know if it works as expected. Looks like it was a copypasta error on my part, the approvalGroup... line exists in an earlier check, I think I just replicated it here and introduced the error.
