### ISSUE TITLE
Umbraco plumber installation breaking when working with LDAP active directory logins

### ISSUE THREAD

**Issue by pyajamanam** [nathanwoulfe/Plumber#60]
Hi Nathan,
I am using workflow installed in umbraco 7.9.2 version, i am using active directory logins.when i login backoffice with active directory and install package showing below error.
please suggest me if am missing anything when installing plumber.
plumberissue
![plumberissue](https://user-images.githubusercontent.com/33079424/44336594-90ba2200-a495-11e8-82d6-355f814a01a7.PNG)

**Comment by nathanwoulfe** [comment]
None of those errors are related to Plumber files, but issue could still be AD-related. 

0.7.11 is a very old Plumber version - should only be using 0.9...

**Comment by nathanwoulfe** [comment]
There's nothing in Plumber that should affect AD - the authenticated user would still have a backoffice identity, so that should be enough.

The owinmiddleware class is only required if you want to use the offline preview - https://github.com/nathanwoulfe/Plumber/blob/master/Workflow/DOCS.md#configuration explains how to either use the included class or add the middleware to an existing startup class.

**Comment by pyajamanam** [comment]
Hi Nathan,

what is the offline preview, if am not wrong is thus related to content preview.what is the purpose of this,
please let me know any scenario

**Comment by pyajamanam** [comment]
Hi Nathan,

I have tried with active directory login and installed with plumber 7.9.0 here is the link it shows error 
umbraco : 7.9.2
created active directory logins and using umbaco identity memebrship provider.
do we have any dependency with custom umbraco identity provider/active directory login implementation.
please let me know things to be needed
https://drive.google.com/file/d/1eJT31lvaSZBNfWcI3bEWcbn1-35cYTzm/view

**Comment by nathanwoulfe** [comment]
There's no AD-specific implementation for Plumber. How you choose to manage Umbraco auth is up to you.

Plumber 0.9 will run on Umbraco versions lower than 7.10. I've just built 0.9.2, with a minimum version requirement of Umbraco 7.10.

For earlier Umbraco versions, you'll need to use an older Plumber version - either the 0.7 or 0.8 release. I can't guarantee either will work as I can't support all old versions. Plumber will be aligned with the two (maybe three) most recent minor Umbraco versions.

**Comment by pyajamanam** [comment]
Nathan,
thanks for update,
if you can able to support the existing bugs fixes to the older version of plumber as well(0.9 below) so that the package will be integrated in umbraco 7.9.2 version without issues.
as of know all the application is set with umbraco 7.9.2,so upgrading umbraco version to 7.12 will affect packages as well as implemented functionalities.

**Comment by nathanwoulfe** [comment]
I can't guarantee being able to do that - it's a lot of work maintaining the latest version without providing backwards support for previous versions (both of Umbraco and Plumber). 

As far as I'm aware, v0.7.11 should be fine in Umbraco 7.9. I'll have a quick look, but can't commit a heap of time to it. Once Plumber is out of beta (planning the next release to be v1), I'll be able to build a release history, but for now, the idea of maintaining old beta versions isn't appealling at all.

**Comment by nathanwoulfe** [comment]
Just ran 0.9.2 on a fresh Umbraco 7.9 install with no issues.
