### ISSUE TITLE
Made of a different color Reject / Resubmitted point

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#62]
Can you made with a different colour the reject / submitted point ?

**Comment by nathanwoulfe** [comment]
Any suggestions as to what/why? Do you mean in the modal or the dashboard timelines?

I've been thinking about changing the timeline in the dashboards to use icons rather than just colour as it's a bit clearer as to the current state.

**Comment by biapar** [comment]
Because I refused a doc and the resubmitted. So the "resubimetted" line is the same color of refused and is not understand if resubmitted or refused.

![image](https://user-images.githubusercontent.com/661517/44511995-78c2e800-a6b9-11e8-90b2-b04cfefca2d5.png)

**Comment by nathanwoulfe** [comment]
I think the thinking there was that rejected and resubmitted are essentially the same state - the task is sitting at the same workflow stage in both cases. I'll find a better way to identify the difference.

**Comment by dmc91** [comment]
Would be great if the row in the table had a background colour code (red rejected, amber resubmitted so the row would change from red to amber once an editor has acted on their comment and resubmitted) to allow administrators to easily see if a change has been resubmitted and pending an action from them.
