### ISSUE TITLE
How to change the buttons text to italian?

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#63]
How to change the buttons text to italian?

**Comment by nathanwoulfe** [comment]
All the buttons, property labels/descriptions, so on make use of Umbraco's localization service - adding a language file to [this folder](https://github.com/nathanwoulfe/Plumber/tree/master/Workflow/App_Plugins/Workflow/Lang) will translate all localized elements into the user's chosen language. 

Have a look in the en-US.xml file for an example, for each key the alias remains unchanged but the value would be updated to the translated text.
