### ISSUE TITLE
Is there an icon or value that show the workflow status of a content?

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#66]
![image](https://user-images.githubusercontent.com/661517/44532909-8ba6de00-a6f4-11e8-9012-29c9b1e827fd.png)

**Comment by nathanwoulfe** [comment]
Not at present - would be nice to have, but not sure how I'd make that work as Plumber doesn't modify node data so couldn't set a property on the content item.

**Comment by biapar** [comment]
I think that you add a new proprierty and change icon colour like this module https://github.com/nathanwoulfe/stately

**Comment by nathanwoulfe** [comment]
Except there is no property on the node to tell if it's in a workflow or not - it would need a db call for every node in the list to get the workflow status. Feels like a lot of overhead.

**Comment by biapar** [comment]
But I think that is enough to expose a value of workflow status for  the node.

**Comment by nathanwoulfe** [comment]
The problem though is that the data returned by Umbraco to build the list view doesn't have any workflow information - the workflow status is stored in different tables and is not associated with a content node outside of a workflow process. 

When you view a content node, the footer buttons are replaced with a Plumber directive, which is able to get the workflow status for the current node - it's not Umbraco returning the content. Only way I can think to make this work would be to bind a directive to the list view, then when it's loaded I'd need to collect the IDs for the displayed nodes, use that to query the status of each node, then map the response back against the list view to inject the icons - without having tried it, that feels like it would be slow and have a negative impact on the load time of the list view

**Comment by nathanwoulfe** [comment]
I think I have this working - it's a bit hacky, but does the job.

**Comment by Matthew-Wise** [comment]
A custom list view might be an option?
https://24days.in/umbraco-cms/2015/custom-listview/

**Comment by nathanwoulfe** [comment]
Still has to fetch the data for the icon in a separate call - I'd probably do that the same way as I explained above, which will be in 0.9.3 (building now). Benefit here is that it doesn't need any changes to work, should just appear on any list view where nodes are in a workflow (hopefully)...

I'm doing a single query to get the id of all nodes in a workflow, then use that to modify the listview. It's one server roundtrip, so impact should be negligible.

**Comment by nathanwoulfe** [comment]
Resolved in v0.9.3
