### ISSUE TITLE
Node No longer Exist: how to remove the old record?

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#67]
I remove a content node, but into the workflow list remain this:

![image](https://user-images.githubusercontent.com/661517/44533160-2dc6c600-a6f5-11e8-9c57-fea381cc646c.png)

How to remove?

**Comment by nathanwoulfe** [comment]
I need to add a filter in the API somewhere to exclude items where the node no longer exists - I want to keep all the db entries for auditing, but there's probably no reason to return items where the node is gone.

**Comment by nathanwoulfe** [comment]
Fix will be in next release (v0.9.3)
