### ISSUE TITLE
ERROR Workflow.Api.TasksController - Error trying to build user workflow tasks list for user 4

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#68]
Why?

2018-08-23 16:53:13,231 [11] ERROR Workflow.Api.TasksController - Error trying to build user workflow tasks list for user 4 
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in Workflow.Api.TasksController.<>c__DisplayClass16_0.<GetFlowsForUser>b__1(WorkflowTaskInstancePoco x)
   in System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   in System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   in System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   in Workflow.Api.TasksController.<GetFlowsForUser>d__16.MoveNext()

**Comment by nathanwoulfe** [comment]
I don't know...

**Comment by biapar** [comment]
I try to read the code for finding the message and so to understand why.
