### ISSUE TITLE
Why Plumber don't send email to approve document?

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#69]
I've configure Umbraco with smtp info, but Plumber don't send email when ther is a workflow change or to approve a document. Why?

**Comment by nathanwoulfe** [comment]
It should. First thing to check - are notifications enabled?

**Comment by biapar** [comment]
Yes. The Umbraco Notification are enabled on the parent node.

**Comment by nathanwoulfe** [comment]
Sorry, I meant in the plumber settings - there's a few fields there that need values

**Comment by nathanwoulfe** [comment]
I'll add email logging into the Plumber logs
