### ISSUE TITLE
Workflow History Error

### ISSUE THREAD

**Issue by blevai13** [nathanwoulfe/Plumber#7]
Hi @nathanwoulfe,

The issue I've discovered related to the database table(WorkflowTaskInstance) and the approval Groups, this happens if a workflow approval group gets deleted, but it has already activities inserted in the table and later when you go back to the history tab in workflow settings you can not view the list because of Object reference error happens. But after I've deleted the records from the above mentioned table that points with idgroup which doesn't exist anymore the history tab starts working again.
Maybe a cascading rule on delete would help, or if you want to save the history then we shouldn't delete the group, just set a disable flag on that group. 

Thanks,
Botond

**Comment by nathanwoulfe** [comment]
Sounds good - will do the latter. Makes sense to preserve history. 

Would probably need to cancel all active workflows assigned to the group at the time of deletion, with a generic comment. Will get to this when I can.

**Comment by nathanwoulfe** [comment]
Deleting a group now sets the deleted flag (column already existed, just wasn't being used). Any active workflows will need to be managed manually, but I'd expect no one should be running around deleting groups without a decent process to manage their tasks. History, group membership etc are all maintained so reporting etc still works fine.
