### ISSUE TITLE
Email templating

### ISSUE THREAD

**Issue by biapar** [nathanwoulfe/Plumber#70]
How to customize the email content? 
I suggest to use a templating system like Postal or similar.
Can I extend plumber with it?

**Comment by nathanwoulfe** [comment]
#52 is intended to cover this - I want to add Razor templating for emails, using the same approach as Umbraco does for Forms workflow stuff.

**Comment by biapar** [comment]
I'm using without problem Postal or https://github.com/lukencode/FluentEmail
Could you want some help on coding?
