### ISSUE TITLE
The workflow-button-group appears even when it should not.

### ISSUE THREAD

**Issue by WillRay** [nathanwoulfe/Plumber#75]
**Describe the bug**
The "Save" button and the "Request Publish" button both appear when creating a new item, while only the "Save" button should appear.

**To Reproduce**
1. In a new Umbraco site, create a content type approval flow for some content type, and associate with an approval group.
2. Create a new item for the content type associated with the approval flow.
3. You will see two buttons in the bottom corner.

**Expected behavior**
I believe that the "Request Publish" button should not be appearing [when creating a new page](https://github.com/nathanwoulfe/Plumber/blob/master/Workflow/App_Plugins/Workflow/Backoffice/views/partials/workflowEditorFooterContentRight.html#L41). Only the "Save" button should appear.

**Screenshots**
Notice how both buttons are appearing on this new item.
![example of both buttons appearing when creating a new item](https://user-images.githubusercontent.com/2540244/46509829-6cb97100-c888-11e8-8c8c-ae48c10236ba.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
We were able to get the expected behaviour by changing `ng-show` to `ng-if` for [this conditional](https://github.com/nathanwoulfe/Plumber/blob/master/Workflow/App_Plugins/Workflow/Backoffice/views/partials/workflowEditorFooterContentRight.html#L41).

**Comment by nathanwoulfe** [comment]
Thanks for investigating - I'll verify it and update accordingly.

**Comment by nathanwoulfe** [comment]
@WillRay I've resolved this in v1.0.1 - thanks again for the detailed report, made my job much easier.
