### ISSUE TITLE
Facing Issue when newly create node by the workflow user

### ISSUE THREAD

**Issue by pyajamanam** [nathanwoulfe/Plumber#77]
**Describe the bug**
I have created a node from the workflow user,am following explicit approval flow. 
so that stage 1 user initiated workflow by creating the new node in the content section.
I am not able to see the button changes form request to publish and then approve changes to proceed next approval.

**To Reproduce**
1.login as workflow user
2. Click on create node and do approval (as it will allow only request to publish but not approve changes )
3. login is stage 2 user and try to approve the newly created node ,which will not allowed in the stage 2 user.

**Expected behavior**
If the user create new node and request to publish and approve changes. it should allow for the next user which is workeing for existing nodes but not the newly created nodes. 

**Screenshots**

**Plumber version**
Which version of Plumber does the bug occur in?
1.0.1 
**Additional context**

also once the stage1 user create new node and request to publish the RTP button is not refreshed.

**Comment by nathanwoulfe** [comment]
This appears to be working correctly when I try it using 1.0.1 => it was explicitly fixed in the v1.0.0 release.

Have you ensured the backoffice is not caching old views/javascript?
