### ISSUE TITLE
Approval group not found for any item if the approval group is set to the root node

### ISSUE THREAD

**Issue by blevai13** [nathanwoulfe/Plumber#79]
**Describe the bug**
The GetPermissionsForNode method return null for the approval group even though the item inherits the workflow configuration from the parent, but with the current configuration the mentioned method above will quit after the first level since the _const_ variable is set to false. My content page is under level 3 and I can send as many time I want the Publish request

**To Reproduce**
1. Set the workflow group on the root node in the backoffice
2. Go to any of the content page under level 1 let's say Home/Products/Phone
3. Click on Request publish enter the message Click submit
4. As a result you would expect to show the Workflow Details button but instead you can send it again and again the Publish Request

**Expected behavior**
After sending the Publish Request the item should enter/follow the workflow process and the Workflow details button and the related message should show up

**Desktop (please complete the following information):**
 - Browser any
 - Version Latest browsers versions

**Plumber version**
1.0.1

**Comment by nathanwoulfe** [comment]
Hi @blevai13, will have a look at this as soon as I can

**Comment by nathanwoulfe** [comment]
v1.0.2 is building now, resolves this issue.
