### ISSUE TITLE
Where is the setting to 'Lock active content'? 

### ISSUE THREAD

**Issue by HistoricEnglandDigitalTeam** [nathanwoulfe/Plumber#81]
**Describe the bug**
Documentation says "Lock active content: how should content in a workflow be managed? Set true or false to determine whether the approval group responsible for the active workflow step can make modifications to the content."

I cant see this option - and it's something we need!

Is this only available in latest version?

**To Reproduce**

1. Go to 'Settings'
2. Cannot see option to set true/false (screen shot below shows entire page)

**Expected behavior**
Able to see an obvious setting to enable active approval group to edit/change content whilst item is at Approval.

**Screenshots**

![image](https://user-images.githubusercontent.com/22772250/47863898-4d165980-ddf0-11e8-8b15-f5097f49e1a2.png)

**Plumber version**
0.7.5

**Comment by nathanwoulfe** [comment]
@HistoricEnglandDigitalTeam this was added in v0.8.0 - latest is v1.0.3, it's worth updating to the latest release to get some other bits and pieces and bugfixes too.

**Comment by HistoricEnglandDigitalTeam** [comment]
Thanks - thought that might be the case. Upgrade is on our 'to do' list.

**Comment by nathanwoulfe** [comment]
Not a problem, I like easily resolved issues!
