### ISSUE TITLE
Interceptor fires for all items, when URL has content in it.

### ISSUE THREAD

**Issue by KevinJump** [nathanwoulfe/Plumber#98]
If your Umbraco site has the work content in the URL. 

e.g 
http://content.client.co.uk

then the interceptor will fire for all pages in the back office (including media) - because the URL has the word content in it. 

the interceptor checks for the presence of content in the URL: using location.href
https://github.com/nathanwoulfe/Plumber/blob/74ffbc272092e58120851cf799f27dc2b125eff1/Workflow/App_Plugins/Workflow/Backoffice/interceptors/workflow.drawerbuttons.interceptor.js#L7

it only needs to check for the presence of content in the location.hash

(PR on its way).

**Comment by nathanwoulfe** [comment]
Hi @KevinJump, haven't had a chance to release this just yet, have another pending issue that I'd like to sort too. Latest build though has this in place.

**Comment by nathanwoulfe** [comment]
Building now, will be on nuget shortly. /N
